server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:orderdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

product-service:
  url: ${PRODUCT_SERVICE_URL:http://localhost:8081}
  connect-timeout-ms: 2000
  read-timeout-ms: 3000

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/orderdb?createDatabaseIfNotExist=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
