server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:productdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/productdb?createDatabaseIfNotExist=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
